const actions = {
  CREATE_GAME: "CREATE_GAME",
  JOIN_GAME: "JOIN_GAME",
  START_GAME: "START_GAME",
  RESET_GAME: "RESET_GAME",
  SET_GAME_CRATED: "SET_GAME_CREATED",
  SET_JOINING_GAME: "SET_JOINING_GAME",
  SELECT_TILE: "SELECT_TILE",
  TILE_SELECTED: "TILE_SELECTED",
  GO_TO_HISTORY: "GO_TO_HISTORY"
};

export { actions }
